/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppCreditCardsRouteImport } from './routes/_app/credit-cards'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDebtsRouteImport } from './routes/_app/debts'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppGoldRouteImport } from './routes/_app/gold'
import { Route as AppReceivablesRouteImport } from './routes/_app/receivables'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppRekapRouteImport } from './routes/_app/rekap'
import { Route as AppRemindersRouteImport } from './routes/_app/reminders'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts_.$id'
import { Route as ApiPublicAppIconRouteImport } from './routes/api/public/app-icon'
import { Route as ApiPublicN8nBackupRouteImport } from './routes/api/public/n8n/backup'
import { Route as ApiPublicN8nBotRouteImport } from './routes/api/public/n8n/bot'
import { Route as ApiPublicN8nCommandRouteImport } from './routes/api/public/n8n/command'
import { Route as ApiPublicN8nMessageRouteImport } from './routes/api/public/n8n/message'
import { Route as ApiPublicN8nOcrRouteImport } from './routes/api/public/n8n/ocr'
import { Route as ApiPublicN8nRemindersRouteImport } from './routes/api/public/n8n/reminders'
import { Route as ApiPublicN8nRemindersEmailRouteImport } from './routes/api/public/n8n/reminders-email'
import { Route as ApiPublicN8nRemindersSendEmailRouteImport } from './routes/api/public/n8n/reminders-send-email'
import { Route as ApiPublicN8nReportRouteImport } from './routes/api/public/n8n/report'
import { Route as ApiPublicN8nSummaryRouteImport } from './routes/api/public/n8n/summary'
import { Route as ApiPublicN8nTransactionsRouteImport } from './routes/api/public/n8n/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditCardsRoute = AppCreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppGoldRoute = AppGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppRekapRoute = AppRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/accounts_/$id',
  path: '/accounts/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicAppIconRoute = ApiPublicAppIconRouteImport.update({
  id: '/api/public/app-icon',
  path: '/api/public/app-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nBackupRoute = ApiPublicN8nBackupRouteImport.update({
  id: '/api/public/n8n/backup',
  path: '/api/public/n8n/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nBotRoute = ApiPublicN8nBotRouteImport.update({
  id: '/api/public/n8n/bot',
  path: '/api/public/n8n/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nCommandRoute = ApiPublicN8nCommandRouteImport.update({
  id: '/api/public/n8n/command',
  path: '/api/public/n8n/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nMessageRoute = ApiPublicN8nMessageRouteImport.update({
  id: '/api/public/n8n/message',
  path: '/api/public/n8n/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nOcrRoute = ApiPublicN8nOcrRouteImport.update({
  id: '/api/public/n8n/ocr',
  path: '/api/public/n8n/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nRemindersRoute = ApiPublicN8nRemindersRouteImport.update({
  id: '/api/public/n8n/reminders',
  path: '/api/public/n8n/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nRemindersEmailRoute =
  ApiPublicN8nRemindersEmailRouteImport.update({
    id: '/api/public/n8n/reminders-email',
    path: '/api/public/n8n/reminders-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nRemindersSendEmailRoute =
  ApiPublicN8nRemindersSendEmailRouteImport.update({
    id: '/api/public/n8n/reminders-send-email',
    path: '/api/public/n8n/reminders-send-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicN8nReportRoute = ApiPublicN8nReportRouteImport.update({
  id: '/api/public/n8n/report',
  path: '/api/public/n8n/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nSummaryRoute = ApiPublicN8nSummaryRouteImport.update({
  id: '/api/public/n8n/summary',
  path: '/api/public/n8n/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nTransactionsRoute =
  ApiPublicN8nTransactionsRouteImport.update({
    id: '/api/public/n8n/transactions',
    path: '/api/public/n8n/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/credit-cards': typeof AppCreditCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/goals': typeof AppGoalsRoute
  '/gold': typeof AppGoldRoute
  '/receivables': typeof AppReceivablesRoute
  '/recurring': typeof AppRecurringRoute
  '/rekap': typeof AppRekapRoute
  '/reminders': typeof AppRemindersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/transactions': typeof AppTransactionsRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/command': typeof ApiPublicN8nCommandRoute
  '/api/public/n8n/message': typeof ApiPublicN8nMessageRoute
  '/api/public/n8n/ocr': typeof ApiPublicN8nOcrRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/n8n/reminders-email': typeof ApiPublicN8nRemindersEmailRoute
  '/api/public/n8n/reminders-send-email': typeof ApiPublicN8nRemindersSendEmailRoute
  '/api/public/n8n/report': typeof ApiPublicN8nReportRoute
  '/api/public/n8n/summary': typeof ApiPublicN8nSummaryRoute
  '/api/public/n8n/transactions': typeof ApiPublicN8nTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/credit-cards': typeof AppCreditCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/goals': typeof AppGoalsRoute
  '/gold': typeof AppGoldRoute
  '/receivables': typeof AppReceivablesRoute
  '/recurring': typeof AppRecurringRoute
  '/rekap': typeof AppRekapRoute
  '/reminders': typeof AppRemindersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/transactions': typeof AppTransactionsRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/command': typeof ApiPublicN8nCommandRoute
  '/api/public/n8n/message': typeof ApiPublicN8nMessageRoute
  '/api/public/n8n/ocr': typeof ApiPublicN8nOcrRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/n8n/reminders-email': typeof ApiPublicN8nRemindersEmailRoute
  '/api/public/n8n/reminders-send-email': typeof ApiPublicN8nRemindersSendEmailRoute
  '/api/public/n8n/report': typeof ApiPublicN8nReportRoute
  '/api/public/n8n/summary': typeof ApiPublicN8nSummaryRoute
  '/api/public/n8n/transactions': typeof ApiPublicN8nTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/credit-cards': typeof AppCreditCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/gold': typeof AppGoldRoute
  '/_app/receivables': typeof AppReceivablesRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/rekap': typeof AppRekapRoute
  '/_app/reminders': typeof AppRemindersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/accounts_/$id': typeof AppAccountsIdRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/n8n/backup': typeof ApiPublicN8nBackupRoute
  '/api/public/n8n/bot': typeof ApiPublicN8nBotRoute
  '/api/public/n8n/command': typeof ApiPublicN8nCommandRoute
  '/api/public/n8n/message': typeof ApiPublicN8nMessageRoute
  '/api/public/n8n/ocr': typeof ApiPublicN8nOcrRoute
  '/api/public/n8n/reminders': typeof ApiPublicN8nRemindersRoute
  '/api/public/n8n/reminders-email': typeof ApiPublicN8nRemindersEmailRoute
  '/api/public/n8n/reminders-send-email': typeof ApiPublicN8nRemindersSendEmailRoute
  '/api/public/n8n/report': typeof ApiPublicN8nReportRoute
  '/api/public/n8n/summary': typeof ApiPublicN8nSummaryRoute
  '/api/public/n8n/transactions': typeof ApiPublicN8nTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/budgets'
    | '/credit-cards'
    | '/dashboard'
    | '/debts'
    | '/goals'
    | '/gold'
    | '/receivables'
    | '/recurring'
    | '/rekap'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/accounts/$id'
    | '/api/public/app-icon'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/command'
    | '/api/public/n8n/message'
    | '/api/public/n8n/ocr'
    | '/api/public/n8n/reminders'
    | '/api/public/n8n/reminders-email'
    | '/api/public/n8n/reminders-send-email'
    | '/api/public/n8n/report'
    | '/api/public/n8n/summary'
    | '/api/public/n8n/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/budgets'
    | '/credit-cards'
    | '/dashboard'
    | '/debts'
    | '/goals'
    | '/gold'
    | '/receivables'
    | '/recurring'
    | '/rekap'
    | '/reminders'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/accounts/$id'
    | '/api/public/app-icon'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/command'
    | '/api/public/n8n/message'
    | '/api/public/n8n/ocr'
    | '/api/public/n8n/reminders'
    | '/api/public/n8n/reminders-email'
    | '/api/public/n8n/reminders-send-email'
    | '/api/public/n8n/report'
    | '/api/public/n8n/summary'
    | '/api/public/n8n/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/accounts'
    | '/_app/budgets'
    | '/_app/credit-cards'
    | '/_app/dashboard'
    | '/_app/debts'
    | '/_app/goals'
    | '/_app/gold'
    | '/_app/receivables'
    | '/_app/recurring'
    | '/_app/rekap'
    | '/_app/reminders'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/transactions'
    | '/_app/accounts_/$id'
    | '/api/public/app-icon'
    | '/api/public/n8n/backup'
    | '/api/public/n8n/bot'
    | '/api/public/n8n/command'
    | '/api/public/n8n/message'
    | '/api/public/n8n/ocr'
    | '/api/public/n8n/reminders'
    | '/api/public/n8n/reminders-email'
    | '/api/public/n8n/reminders-send-email'
    | '/api/public/n8n/report'
    | '/api/public/n8n/summary'
    | '/api/public/n8n/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicAppIconRoute: typeof ApiPublicAppIconRoute
  ApiPublicN8nBackupRoute: typeof ApiPublicN8nBackupRoute
  ApiPublicN8nBotRoute: typeof ApiPublicN8nBotRoute
  ApiPublicN8nCommandRoute: typeof ApiPublicN8nCommandRoute
  ApiPublicN8nMessageRoute: typeof ApiPublicN8nMessageRoute
  ApiPublicN8nOcrRoute: typeof ApiPublicN8nOcrRoute
  ApiPublicN8nRemindersRoute: typeof ApiPublicN8nRemindersRoute
  ApiPublicN8nRemindersEmailRoute: typeof ApiPublicN8nRemindersEmailRoute
  ApiPublicN8nRemindersSendEmailRoute: typeof ApiPublicN8nRemindersSendEmailRoute
  ApiPublicN8nReportRoute: typeof ApiPublicN8nReportRoute
  ApiPublicN8nSummaryRoute: typeof ApiPublicN8nSummaryRoute
  ApiPublicN8nTransactionsRoute: typeof ApiPublicN8nTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-cards': {
      id: '/_app/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof AppCreditCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gold': {
      id: '/_app/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof AppGoldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables': {
      id: '/_app/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rekap': {
      id: '/_app/rekap'
      path: '/rekap'
      fullPath: '/rekap'
      preLoaderRoute: typeof AppRekapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reminders': {
      id: '/_app/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts_/$id': {
      id: '/_app/accounts_/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/app-icon': {
      id: '/api/public/app-icon'
      path: '/api/public/app-icon'
      fullPath: '/api/public/app-icon'
      preLoaderRoute: typeof ApiPublicAppIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/backup': {
      id: '/api/public/n8n/backup'
      path: '/api/public/n8n/backup'
      fullPath: '/api/public/n8n/backup'
      preLoaderRoute: typeof ApiPublicN8nBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/bot': {
      id: '/api/public/n8n/bot'
      path: '/api/public/n8n/bot'
      fullPath: '/api/public/n8n/bot'
      preLoaderRoute: typeof ApiPublicN8nBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/command': {
      id: '/api/public/n8n/command'
      path: '/api/public/n8n/command'
      fullPath: '/api/public/n8n/command'
      preLoaderRoute: typeof ApiPublicN8nCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/message': {
      id: '/api/public/n8n/message'
      path: '/api/public/n8n/message'
      fullPath: '/api/public/n8n/message'
      preLoaderRoute: typeof ApiPublicN8nMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/ocr': {
      id: '/api/public/n8n/ocr'
      path: '/api/public/n8n/ocr'
      fullPath: '/api/public/n8n/ocr'
      preLoaderRoute: typeof ApiPublicN8nOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/reminders': {
      id: '/api/public/n8n/reminders'
      path: '/api/public/n8n/reminders'
      fullPath: '/api/public/n8n/reminders'
      preLoaderRoute: typeof ApiPublicN8nRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/reminders-email': {
      id: '/api/public/n8n/reminders-email'
      path: '/api/public/n8n/reminders-email'
      fullPath: '/api/public/n8n/reminders-email'
      preLoaderRoute: typeof ApiPublicN8nRemindersEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/reminders-send-email': {
      id: '/api/public/n8n/reminders-send-email'
      path: '/api/public/n8n/reminders-send-email'
      fullPath: '/api/public/n8n/reminders-send-email'
      preLoaderRoute: typeof ApiPublicN8nRemindersSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/report': {
      id: '/api/public/n8n/report'
      path: '/api/public/n8n/report'
      fullPath: '/api/public/n8n/report'
      preLoaderRoute: typeof ApiPublicN8nReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/summary': {
      id: '/api/public/n8n/summary'
      path: '/api/public/n8n/summary'
      fullPath: '/api/public/n8n/summary'
      preLoaderRoute: typeof ApiPublicN8nSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/transactions': {
      id: '/api/public/n8n/transactions'
      path: '/api/public/n8n/transactions'
      fullPath: '/api/public/n8n/transactions'
      preLoaderRoute: typeof ApiPublicN8nTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCreditCardsRoute: typeof AppCreditCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppGoldRoute: typeof AppGoldRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppRekapRoute: typeof AppRekapRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppAccountsIdRoute: typeof AppAccountsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCreditCardsRoute: AppCreditCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppGoldRoute: AppGoldRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppRekapRoute: AppRekapRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppAccountsIdRoute: AppAccountsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicAppIconRoute: ApiPublicAppIconRoute,
  ApiPublicN8nBackupRoute: ApiPublicN8nBackupRoute,
  ApiPublicN8nBotRoute: ApiPublicN8nBotRoute,
  ApiPublicN8nCommandRoute: ApiPublicN8nCommandRoute,
  ApiPublicN8nMessageRoute: ApiPublicN8nMessageRoute,
  ApiPublicN8nOcrRoute: ApiPublicN8nOcrRoute,
  ApiPublicN8nRemindersRoute: ApiPublicN8nRemindersRoute,
  ApiPublicN8nRemindersEmailRoute: ApiPublicN8nRemindersEmailRoute,
  ApiPublicN8nRemindersSendEmailRoute: ApiPublicN8nRemindersSendEmailRoute,
  ApiPublicN8nReportRoute: ApiPublicN8nReportRoute,
  ApiPublicN8nSummaryRoute: ApiPublicN8nSummaryRoute,
  ApiPublicN8nTransactionsRoute: ApiPublicN8nTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
